spring:
  main:
    banner-mode: off

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: username
    password: password
  batch:
    initalize-schema: ALWAYS
    job:
      enabled: false

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB